source "https://ruby.taobao.org"
# source "https://rubygems.org" # Use rubygems if you're not in China

gem 'sinatra', '~> 2.0.0.rc2', require: 'sinatra/base'
gem 'rake'
<%- unless @no_database -%>
gem 'activerecord'
<%- if @database == 'postgresql' || @database == 'pg' -%>
gem 'pg'
<%- elsif @database == 'sqlite' -%>
gem 'sqlite3'
<%- elsif @database == 'mongo' || @database == 'mongodb' -%>
gem 'mongoid'
<%- else -%>
# default database: mysql
gem 'mysql2', '~> 0.4.3'
<%- end -%>
<%- if @redis -%>
gem 'redis'
<%- end -%>
<%- end -%>

<%- unless @no_views -%>
# with assetpack, using sass, and uglifier
# assetpack support by compass configure when using scss/sass import
gem 'sinatra-assetpack', require: 'sinatra/assetpack'
gem 'compass'
gem 'sass'
gem 'uglifier'
<%- end %>

<%- unless @no_views -%>
# Rack csrf gem for authentication of form post action
gem 'rack_csrf', require: "rack/csrf"
<%- end %>

group :development, :test do
  gem 'shotgun'
  gem 'pry'
  gem 'racksh'
  gem 'rspec'
  gem 'guard-rspec'
  gem 'guard-livereload'
  gem 'terminal-notifier-guard'
  gem 'database_cleaner'
end

group :development, :production do
  # web app servers
  # gem 'unicorn'
  # gem 'rainbows'
  gem 'puma'
end
